trigger:
- nuget

pool:
  vmImage: 'windows-latest'

variables:
  PROJECT_PATH: '$(Build.SourcesDirectory)/NORM.Guard/NORM.Guard.csproj'
  PACKAGE_OUTPUT_DIRECTORY: '$(Build.ArtifactStagingDirectory)/output'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
- job: Deploy
  displayName: 'Deploy to NuGet'
  steps:
  - task: Checkout@1
    displayName: 'Checkout code'

  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore $(PROJECT_PATH)
    displayName: 'Restore packages'

  - script: |
      dotnet build $(PROJECT_PATH) --configuration Release --no-restore
    displayName: 'Build project'

  - task: GetVersion@1
    displayName: 'Get version'
    inputs:
      versionSpec: '$(Build.BuildId)'

  - script: |
      dotnet pack $(PROJECT_PATH) --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=$(Build.BuildId) --output $(PACKAGE_OUTPUT_DIRECTORY)
    displayName: 'Pack project'

  - task: NuGetCommand@2
    displayName: 'Push package to NuGet'
    inputs:
      command: 'push'
      packagesToPush: '$(PACKAGE_OUTPUT_DIRECTORY)/*.nupkg'
      nuGetFeedType: 'External'
      externalFeedUrl: '$(NUGET_SOURCE_URL)'
      apiKey: $(NUGET_AUTH_TOKEN)
