name: "Deploy to NuGet"

on: 
  push:
    branches:
      - nuget

env:
  PROJECT_PATH: '${{ github.workspace }}/NORM.Guard/NORM.Guard.csproj'
  PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/output'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy to NuGet'
    runs-on: 'windows-latest'
    
    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'
    
    - name: 'Set up .NET'
      uses: 'actions/setup-dotnet@v1'
      with:
        dotnet-version: '9.0.x'
    
    - name: 'Restore dependencies'
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    
    - name: 'Push package to NuGet'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
    
