name: "Deploy to NuGet"

on: ["push"]

env:
  PROJECT_PATH: 'NORM.Guard/NORM.Guard.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
    
      - name: 'Install dotnet'
        uses: 'actions/setup-dotnet@v1'
        with:
          dotnet-version: '9.0.x'
    
      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
    
      - name: 'Build packages'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    
      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}

